server:
  port: 80

logging:
  level:
    dangqu: debug

spring:
  datasource:
    username: postgres
    password: bestadmin
    url: jdbc:postgresql://119.3.8.246:5432/automation
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://test.powertrade.lumicable.cn/useridentity
          key-set-uri: https://test.powertrade.lumicable.cn/useridentity/.well-known/openid-configuration/jwks
        provider:
          uaa:
            issuer-uri: https://test.powertrade.lumicable.cn/useridentity
